services:
  app:
    image: ghcr.io/reversed-r/todoroki-client:latest
    restart: always
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.services.app.loadbalancer.server.scheme: http
      traefik.http.routers.app.rule: Host(`todo.reversed-r.dev`)
      traefik.http.routers.app.entrypoints: websecure,web
      traefik.http.routers.app.tls.certResolver: leresolver
      traefik.http.routers.app.service: app

networks:
  traefik:
    name: traefik
    external: true
