services:
  app:
    image: ghcr.io/reversed-r/todoroki-client:latest
    restart: always
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.services.todoroki-client.loadbalancer.server.scheme: http
      traefik.http.routers.todoroki-client.rule: Host(`todo.reversed-r.dev`)
      traefik.http.routers.todoroki-client.entrypoints: websecure,web
      traefik.http.routers.todoroki-client.tls.certResolver: leresolver

networks:
  traefik:
    name: traefik
    external: true
